<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="0" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Tests" duration-ms="10" started-at="2017-11-13T12:56:05Z" finished-at="2017-11-13T12:56:05Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="10" started-at="2017-11-13T12:56:05Z" finished-at="2017-11-13T12:56:05Z">
      <class name="com.sz.SampleTestNgTest">
        <test-method status="FAIL" signature="initTestSuite()[pri:0, instance:com.sz.SampleTestNgTest@783e6358]" name="initTestSuite" is-config="true" duration-ms="20" started-at="2017-11-13T15:56:05Z" finished-at="2017-11-13T15:56:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at sun.misc.MetaIndex.mayContain(Unknown Source)
	at sun.misc.URLClassPath$JarLoader.getResource(Unknown Source)
	at sun.misc.URLClassPath.getResource(Unknown Source)
	at sun.misc.URLClassPath.getResource(Unknown Source)
	at java.lang.ClassLoader.getBootstrapResource(Unknown Source)
	at java.lang.ClassLoader.getResource(Unknown Source)
	at java.lang.ClassLoader.getResource(Unknown Source)
	at java.net.URLClassLoader.getResourceAsStream(Unknown Source)
	at java.lang.Class.getResourceAsStream(Unknown Source)
	at com.sz.SuiteConfiguration.getCapabilities(SuiteConfiguration.java:33)
	at com.sz.TestNgTestBase.initTestSuite(TestNgTestBase.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTestSuite -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.sz.SampleTestNgTest@783e6358]" name="tearDown" is-config="true" duration-ms="60" started-at="2017-11-13T15:56:05Z" finished-at="2017-11-13T15:56:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.sz.SampleTestNgTest -->
    </test> <!-- Test1 -->
  </suite> <!-- Tests -->
</testng-results>
